### ISSUE TITLE
Capture id of the user taking the action

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-event-exchange#10]
This is necessary for audit control/change log.

Example for deleting a queue:

```
Exchange    amq.rabbitmq.event
Routing Key queue.deleted
Redelivered ○
Properties  
timestamp:  1454028844518415
delivery_mode:  2
headers:    
name:   adadawd
vhost:  /
Payload
0 bytes
Encoding: string

```

There is no user id.

**Comment by michaelklishin** [comment]
For some operations it makes sense and wouldn't require a lot of changes. `queue.*` fall into that category.

**Comment by uvzubovs** [comment]
Certainly. Please add it wherever appropriate. 

Also please add vhost wherever missing and appropriate, e.g. binding.* as stated in another issue. Creation of a binding may be considered eavesdropping, and, so, is critical for audit control.

**Comment by uvzubovs** [comment]
Is this on the back burner now? I had assumed this has already been released, and just now realized that it hasn't.

**Comment by jrlog** [comment]
I'd like to register interest in this also.

**Comment by dcorbacho** [comment]
Note regarding https://github.com/rabbitmq/rabbitmq-event-exchange/issues/10#issuecomment-176564266: `vhost` is part of the binding details since 3.6.2, see https://github.com/rabbitmq/rabbitmq-server/pull/800
