### ISSUE TITLE
Add high-resolution event timestamp to event info in application headers

### ISSUE THREAD

**Issue by vitaly-krugl** [rabbitmq/rabbitmq-event-exchange#12]
PR #11 restored the frame header's timestamp to second-level resolution for compliance with AMQP specification per issue #8.

Since high-resolution event timestamps are important for debugging, a high-resolution timestamp should be added to the event info in application headers, where it won't conflict with AMQP spec, along with appropriate documentation. Need to pick a sensible name for the new timestamp.

**Comment by michaelklishin** [comment]
Resolved in #19.
