### ISSUE TITLE
Add vhost information to the policy.* events

### ISSUE THREAD

**Issue by MarcialRosales** [rabbitmq/rabbitmq-event-exchange#17]
The client has a large number of vhosts and want to process policy events (policy.set & policy.cleared) per vhost. Right now it is not  possible because these events do not carry a vhost attribute.

Is it possible to add vhost information to these events?

**Comment by michaelklishin** [comment]
Resolved in https://github.com/rabbitmq/rabbitmq-server/pull/800.
