### ISSUE TITLE
Queue process is weird state after upgrade to 3.6.2

### ISSUE THREAD

**Issue by magec** [rabbitmq/rabbitmq-event-exchange#24]
After an upgrade from 3.5.3 we faced an bug with event exchange plugin. 

We always keep a queue connected to creation/destroy events using the plugin. That queue is set to durable and is a mirror queue. It has several consumers connected to it.

The thing was that, after an upgrade, that queue went to a corrupt state, we could neither delete it ,nor consume from it. The counters in the management console went to NaN, etc. We fixed the issue by getting the node where the queue was allocated out of the cluster. Deleting its mnesia files and rejoining the cluster. We though it was just a thing related to rabbit upgrade, but after a restart, it happened again. I cannot reproduce the issue in our staging environments. This lead us to downgrade and go back to 3.5.3.

**Comment by michaelklishin** [comment]
Do you still have logs of that node? Can you post them?

3rd party plugins such as this one must be upgrade together with RabbitMQ. In fact, if Debian or RPM package is used, the plugins are not currently migrated during the upgrade at all.

**Comment by magec** [comment]
I did change the plugin as well.

**Comment by michaelklishin** [comment]
Are the logs still available? If not I'm afraid we cannot help.

**Comment by michaelklishin** [comment]
Also, by "change" what exactly do you mean? Where was the plugin `.ez` used with `3.6.2` obtained from?

**Comment by michaelklishin** [comment]
Was queue mirroring enabled for the queue in question? This sounds like https://github.com/rabbitmq/rabbitmq-server/issues/812 that has nothing to do with this plugin.

**Comment by magec** [comment]
Uhmm, I use debian packages, and I bet in last release exchange_events was included in the distribution. The logs are this:

```
=INFO REPORT==== 14-Jun-2016::10:38:34 ===
Mirrored queue 'queueEvents' in vhost 'parrot': Slave <rabbit@mq02.1.27908.0> saw deaths of mirrors <rabbit@mq01.3.5177.0>

=INFO REPORT==== 14-Jun-2016::10:38:34 ===
Mirrored queue 'queueEvents' in vhost 'parrot': Promoting slave <rabbit@mq02.1.27908.0> to master

** Reason for termination == 
** {timeout_value,
       [{rabbit_mirror_queue_master,'-stop_all_slaves/2-lc$^1/1-1-',3,
            [{file,"src/rabbit_mirror_queue_master.erl"},{line,217}]},
        {rabbit_mirror_queue_master,stop_all_slaves,2,
            [{file,"src/rabbit_mirror_queue_master.erl"},{line,217}]},
        {rabbit_mirror_queue_master,delete_and_terminate,2,
            [{file,"src/rabbit_mirror_queue_master.erl"},{line,205}]},
        {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,247}]}]}
** In 'terminate' callback with reason ==
** normal

Mirrored queue 'queueEvents' in vhost 'parrot': Stopping all nodes on master shutdown since no synchronised slave is available



AND THEN


=ERROR REPORT==== 14-Jun-2016::10:44:40 ===
Channel error on connection <0.12327.2> (10.0.2.6:38012 -> 10.0.21.112:5672, vhost: 'parrot', user: 'parrot'), channel 1:
operation queue.declare caused a channel exception not_found: "failed to perform operation on queue 'queueEvents' in vhost 'parrot' due to timeout"

```
Seems to be what you comment. Thanks for the help! I will reconsider an upgrde after that gets into the release.

**Comment by michaelklishin** [comment]
Yes, just wait for 3.6.3.
