### ISSUE TITLE
Passcode from STOMP CONNECT frame

### ISSUE THREAD

**Issue by MichalBliznak** [rabbitmq/rabbitmq-event-exchange#29]
Hello, I'd like to know if also STOMP CONNECT passcode header can be propagated via RabbitMQ event exchange plugin to a connected consumer, e.g. as a part of connection.* or user.authentication.* events. If not supported by default, is it possible to modify the plugin to allow this?

**Comment by michaelklishin** [comment]
It becomes connection event password, which I'm not sure if we include, or whether it's a good idea to include it but there should be nothing specific to STOMP in this case.
