### ISSUE TITLE
plugin seem doesn't working

### ISSUE THREAD

**Issue by ghost** [rabbitmq/rabbitmq-event-exchange#3]
I installed rabbitmq_event_exchange on ubuntu by 
     1. downloaded: rabbitmq_event_exchange-3.3.x-12eef624.ez, 
     2. put it into dir:  /rabbitmq_server-3.3.4/plugins
     3. enabled it  by command: rabbitmq-pluings enable rabbitmq_event_exchange

and that was no exchange "amq.rabbitmq.event", what's wrong, please give me some suggestions.

**Comment by michaelklishin** [comment]
With 3.3.x you need to restart RabbitMQ, live plugin activation was added in 3.4.x (and even then, when you drop a new plugin into the plugins dir, a restart will be required).
