### ISSUE TITLE
Plugin doesn't provide a new style configuration schema

### ISSUE THREAD

**Issue by vimal4david** [rabbitmq/rabbitmq-event-exchange#31]
I am configuring [RabbitMQ](https://www.rabbitmq.com/) with the [rabbitmq_event_exchange](https://github.com/rabbitmq/rabbitmq-event-exchange) plugin to listen to RabbitMQ [queue creation](https://github.com/rabbitmq/rabbitmq-event-exchange#rabbitmq-broker) events. By default, the plugin is creating an exchange named 'amq.rabbitmq.event' in the default vhost(/) . But, I am trying to change vhost to 'test' (custom vhost created by me) As per the [instructions](https://github.com/rabbitmq/rabbitmq-event-exchange#configuration) from the plugin page, I added a property rabbitmq_event_exchange.vhost= test in my rabbitmq.conf file. But, the plugin doesn't provide a new style configuration schema, so it didn't worked. I am allowed to use only classic config format.

Ref: https://groups.google.com/forum/#!topic/rabbitmq-users/Z7_5WGc2ubE

**Comment by michaelklishin** [comment]
It was never actually backported to `v3.7.x`, see #43. It is now, for `3.7.21`.
