### ISSUE TITLE
Non-compliant timestamp format in content header?

### ISSUE THREAD

**Issue by vitaly-krugl** [rabbitmq/rabbitmq-event-exchange#8]
A user of the Haigha AMQP client library reported getting the value of the timestamp in microseconds in the content header from rabbitmq-event-exchange - see https://github.com/agoragames/haigha/pull/88#discussion_r39133199 .

I also came across this complaint about the same problem in another amqp client: https://github.com/bakkerthehacker/bramqp/issues/44

If that user is correct, it would mean that rabbitmq-event-exchange plugin is violating the amqp0-9-1 specification that defines the timestamp to be a 64-bit "POSIX time_t", which is expressed in seconds (not microseconds).

Deviating from the AMQP spec breaks client implementations and/or interferes with their timestamp format parsing/validation logic. A safe alternative would be to place the higher-resolution timestamp value as a property in the headers table along with the other Props.

I also posted a question about this in https://groups.google.com/forum/#!topic/rabbitmq-users/_4ZRm8vX73g

**Comment by michaelklishin** [comment]
@vitaly-krugl a fix will be in `3.6.1`. Thanks again for reporting.

**Comment by vitaly-krugl** [comment]
Thanks for the heads-up, @michaelklishin. I also left you feedback in PR #11
