### ISSUE TITLE
Add vhost information to binding events

### ISSUE THREAD

**Issue by thejuan** [rabbitmq/rabbitmq-event-exchange#9]
we have a number of vhosts and want to process binding events per vhost
Is it possible to add vhost information to these events?

**Comment by uvzubovs** [comment]
Indeed, we need this data in order to know which binding was affected. We have several vhosts with the equally named queues. Thanks in advance!

**Comment by MarcialRosales** [comment]
Would it be possible to extend it to policy events too? We are building an operations tool for a client (Bosch) and we need to monitor policy activity. The client has multiple vhosts in a single cluster.
Many thanks in advance!

**Comment by uvzubovs** [comment]
+1
Absolutely necessary. Thanks

**Comment by michaelklishin** [comment]
Resolved in https://github.com/rabbitmq/rabbitmq-server/pull/800.
